### ISSUE TITLE
Wrong Screen Shots

### ISSUE THREAD

**Issue by 3ative** [home-assistant-community-themes/material-dark-pink#2]
Screen shots are Green themed :)

**Comment by maartenpaauw** [comment]
Hello @3ative! Thanks for opening a issue. 

This theme isn't completely done yet. There is a pull request opened for the initial setup #1. The new screenshots are located in the `docs/` directory within the `setup` branch. 

This repository is created based on a template (which can be found here: https://github.com/home-assistant-community-themes/template). This template contains a basic green theme. Thats why there are green themed sceenshots right now.

**Comment by 3ative** [comment]
@maartenpaauw 
Cool, no worries... just wondered if you knew. Cheers
