### ISSUE TITLE
Enabled toggle control is the same colour as the background

### ISSUE THREAD

**Issue by devopsleigh** [home-assistant-community-themes/material-dark-pink#5]
When a toggle is enabled, the toggle changes to the same colour as the background.

![image](https://user-images.githubusercontent.com/31065424/71551265-006de480-29db-11ea-9540-f6321a626499.png)

**Comment by devopsleigh** [comment]
Is there an order of precedence for the theme yaml? I moved primary-color to the end and it looks normal again.

**Comment by devopsleigh** [comment]
Nope, it just coincided with changing the colour to var(--accent). NVM!

**Comment by maartenpaauw** [comment]
I saw that you solved the issue via the email conversation. Good to hear 👍
